### ISSUE TITLE
Missing pre-trained model

### ISSUE THREAD

**Issue by rodonguyen** [Sbrunoberenguel/FreDSNet#1]
Hi,
I'm trying to run the model on Example images (using `python3 inference.py`) but the model weights seem to not be found. Below is the error message:
```
FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/FreDSNet_weights.pth'
```
Is the pre-trained model publicly available? If yes, how can I download the FreDSNet_weights.pth? 

Thank you in advance.
Rodo

**Comment by Sbrunoberenguel** [comment]
Hello Rodo,

the pre-trained weights can be found in the ReadME file in an external link. Here you have this link so you can find these weights more easily:
https://drive.google.com/file/d/1m77CfwUGj6DlxRjheoO1sRxPdKewUbMK/view?usp=sharing

Make sure to save the weights in a 'ckpt' folder (or choose the correct weights' path in the inference program)

Best regards

**Comment by rodonguyen** [comment]
Thank you. I read too fast and missed the tiny hyperlink.
