### ISSUE TITLE
semantic segmentation labels

### ISSUE THREAD

**Issue by zcyyyy24** [Sbrunoberenguel/FreDSNet#5]
Hi! 
Rencently I have ran the project successfully, and the results in the example RGB images was great. 
But when I want to run the model on my outdoor data, the semantic segmentation results were poor, like below. Then I changed the color_code to suit my dataset, it also did't work out. If I want to get the depth and segmentation results on my real world data, where need to modify?
Could you help me, please!
![frame_0_seg](https://github.com/Sbrunoberenguel/FreDSNet/assets/152855926/c7f80b18-be50-4a83-8e5a-41af9858b3a1)
![image](https://github.com/Sbrunoberenguel/FreDSNet/assets/152855926/f34c6883-fe6e-46f3-b659-04a0def5513a)

**Comment by Sbrunoberenguel** [comment]
Hello!
The color code is only used for "pretty" visualization, it does not change the network performance.
The image you used (or at least the example) is from an outdoor environment. The network has been trained on indoor data (as can be seen in the color code where each color represent an indoor class).
If  you want FreDSNet to work on outdoor environments, you have to train it with the classes you want to segment. Today (and in the close future), the implementation and weights for outdoor environments are not in this repository.
Best regards

**Comment by zcyyyy24** [comment]
Thanks for your early reply! 
Now I know the model was trained on the indoor dataset. Could you recommend some outdoor panorama dataset if I want to train the semantic segmentation? What's more, do you know other model which can deal with the outdoor panorama image to get both depth and segmentation?
I am appreciated that you can help me a lot.
















At 2024-01-08 17:28:03, "Bruno Berenguel-Baeta" ***@***.***> wrote:

Hello!
The color code is only used for "pretty" visualization, it does not change the network performance.
The image you used (or at least the example) is from an outdoor environment. The network has been trained on indoor data (as can be seen in the color code where each color represent an indoor class).
If you want FreDSNet to work on outdoor environments, you have to train it with the classes you want to segment. Today (and in the close future), the implementation and weights for outdoor environments are not in this repository.
Best regards

**Comment by Sbrunoberenguel** [comment]
Up to my knowledge, there is no other network that jointly obtains depth and segmentation from panoramas (indoor or outdoor).
If you have more questions about this topic, you can read my paper, linked in the repository, or ask me any question directly in my email: berenguel@unizar.es
Best regards
